apiVersion: v1
kind: Secret
metadata:
  name: azure
  namespace: [branch]
data:
  azurestorageaccountname: YmFja3Vwc2xlZGdlcmxlb3BhcmQ=
  azurestorageaccountkey: dk5QdkZ6Z1Rpb01IS3plb0pFTmRwd3NlY3RXWUZtL0VGQ1VDMzEzRTdpbTJaajFVOGp6Qi9pMnVOcGdzVVk3OFlsUGVzWTEyejVVbmtUNmttWHZlZlE9PQ==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-backup
  namespace: [branch]
type: Opaque
data:
  name: c3VwZXJVc2Vy
  pass: dGhpc19pc19ub3RfeW91cl9wYXNzd29yZA==
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: [branch]
  labels:
    app: mongo-backup
spec:
  schedule: "@daily"
  #schedule: "0-59/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - name: mongo-backup
              image: mongo:4
              volumeMounts:
                - name: mongo-backup
                  mountPath: /dump
                  subPath: vaccination-[branch]
              imagePullPolicy: Always
              env:
                - name: DB
                  value: admin
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongo-backup
                      key: name
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongo-backup
                      key: pass
                - name: PROJECT
                  value: vaccination-[branch]
              command: ["/bin/bash"]
              args: ["-c", "Time=$(date  +%Y.%m.%d-%H-%M-%S); mongodump --host mongo.[branch] --port 27117 --username $(USERNAME) --password $(PASSWORD) -o /dump/$(PROJECT).${Time}"]
          restartPolicy: Never
          volumes:
            - name: mongo-backup
              azureFile:
                secretName: azure
                shareName: backup
